name: Package Electron

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        shell: bash
        run: |
          npm install --legacy-peer-deps
      - name: generate windows installer
        run: npm run make
      - name: upload windows installer
        shell: bash
        run: |
          ls
          ls dist/
