name: Package Electron
on: pull_request
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag:  'true'
      - name: npm install
        shell: bash
        run: |
          npm install -g npm
          npm install
      - name: generate windows installer
        run: npm run make
      - name: upload windows installer
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64
