name: Package Electron
on: pull_request
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
      - name:  'Automated Version Bump'
        if: steps.check.outputs.changed == 'false'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag:  'true'
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: npm install
        shell: bash
        run: |
          npm install -g npm
          npm install
      - name: generate windows installer
        run: npm run make
      - name: upload windows installer
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64
