name: Package Electron
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: npm install
        shell: bash
        run: |
          npm install --legacy-peer-deps
      - name: generate windows installer
        run: npm run package
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
